
import pandas as pd
import json

def median_value():
    user_median_dic = {}
    item_median_dic = {}
    file = './data/train_data_header_test.csv'
    print('---> {} <--- reading succeeded.'.format(file))
    df = pd.read_csv(file,encoding='gbk')
    ######################## user ###################################################
    user_lst = ['CostFrom','CostTo','Room','Sex',]

    for user in user_lst[:-1]:
        try:
            x = round(df[user].median(), 2)
            user_median_dic[user] = x
        except Exception as e:
            print(e)
            raise Exception('数据格式错误，请检查并修改！！！')
    user_median_dic['Room'] = 2.00
    ######################## item #################################################
    item_lst = ['BuildingSize','FloorNumber','RoomCount','HallCount','ToiletCount',
                'Price','TotalPrice','EstateName','City_Name','Sq_Name']

    for item in item_lst[:7]:
        try:
            x = round(df[item].median(), 2)
            item_median_dic[item] = x
        except Exception as e:
            print(e)
            raise Exception('数据格式错误，请检查并修改！！！')
    ######################### save to json #####################################################
    with open("./data/user_median_dic.json", "w+") as u:
        json.dump(user_median_dic,u)
        print('---> ./data/user_median_dic.json (generated by fill_empty.py) <--- saving succeeded.')

    with open("./data/item_median_dic.json", "w+") as i:
        json.dump(item_median_dic,i)
        print('---> ./data/item_median_dic.json (generated by fill_empty.py) <--- saving succeeded.')

if __name__ == "__main__":
    median_value()





